baseurl = "/"
defaultContentLanguage = "en"
enableEmoji = true
title = "María Paula Caldas"
theme = "hugo-xmin"
googleAnalytics = "UA-142117256-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
enable_highlightjs = "false"

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[params]
    description = "María Paula's blog"
    githubSource = "https://github.com/mpaulacaldas/mpaulacaldas/blob/master/content/"
    footer = "&copy; [María Paula Caldas](https://mpaulacaldas.com) 2020 | [Github](https://github.com/mpaulacaldas) | [Twitter](https://twitter.com/mapaulacaldas)"

[languages]
  [languages.en]
    languageCode = "en"
  [languages.es]
    languageCode = "es"
  [languages.fr]
    languageCode = "fr"

[[languages.en.menu.main]]
    url    = "/"
    name   = "Blog"
    weight = 1
[[languages.es.menu.main]]
    url    = "/"
    name   = "Bitácora"
    weight = 1
[[languages.fr.menu.main]]
    url    = "/"
    name   = "Blogue"
    weight = 1

[[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[languages.es.menu.main]]
    name = "Acerca"
    url = "/about/"
    weight = 2
[[languages.fr.menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 2
